FROM python:3.8
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
COPY kafka/executioner.py /app/executioner.py
COPY kafka/config.py /app/config.py
WORKDIR /app

CMD ["python", "executioner.py"]

